# ha0_pclock to rd_clock
set_false_path -from [get_clocks -of_objects [get_pins b/pcihip0/psl_pcihip0_inst/inst/gt_top_i/phy_clk_i/bufg_gt_userclk/O]] -to [get_clocks -of_objects [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/kernel_clock_gen/inst/BUFGCE_DIV_CLK1_inst/O}]]
# rd_clock to ha0_pclock
#set_false_path -from [get_clocks -of_objects [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/kernel_clock_gen/inst/BUFGCE_DIV_CLK1_inst/O}]] -to [get_clocks -of_objects [get_pins b/pcihip0/psl_pcihip0_inst/inst/gt_top_i/phy_clk_i/bufg_gt_userclk/O]]


# Reset from readprob to readprob fifo
set_false_path -from [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/rs_reg[readprob_delay_rst]_replica_4/C}] -to [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/readprob_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v8_fifo.fblk/rst_val_sym.gextw_sym[1].inst_extd/gmult_prim.gbi_chain.gp1[2].gbi_last.inst_prim/gf36e2_inst.sngfifo36e2/RST}]
set_false_path -from [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/shift_readprob_r_reg[reset]/C}] -to [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/readprob_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v8_fifo.fblk/rst_val_sym.gextw_sym[2].inst_extd/gmult_prim.gbi_chain.gp1[1].gbi_top.top_inst_prim/gf36e2_inst.sngfifo36e2/RST}]
set_false_path -from [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/rs_reg[readprob_delay_rst]_replica/C}] -to [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/readprob_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v8_fifo.fblk/rst_val_sym.gextw_sym[3].inst_extd/gmult_prim.gbi_chain.gp1[2].gbi_last.inst_prim/gf36e2_inst.sngfifo36e2/RST}]
set_false_path -from [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/rs_reg[readprob_delay_rst]_replica_4/C}] -to [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/readprob_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v8_fifo.fblk/rst_val_sym.gextw_sym[3].inst_extd/gmult_prim.gbi_chain.gp1[1].gbi_top.top_inst_prim/gf36e2_inst.sngfifo36e2/RST}]
set_false_path -from [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/shift_readprob_r_reg[reset]_replica/C}] -to [get_pins {a0/action_w/action_0/arrow_pairhmm_inst/pairhmm_gen[0].pairhmm_inst/readprob_fifo/U0/inst_fifo_gen/gconvfifo.rf/gbi.bi/v8_fifo.fblk/rst_val_sym.gextw_sym[4].inst_extd/gmult_prim.gbi_chain.gp1[2].gbi_last.inst_prim/gf36e2_inst.sngfifo36e2/RST}]
